services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
      XDEBUG_MODE: "debug"
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003 start_with_request=yes"
      XDEBUG_SESSION: "PHPSTORM"
    depends_on:
      - mariadb
      - mysql

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: symfony_mariadb
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3308:3306"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: symfony_mysql
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root_secret
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOSTS: "mariadb,mysql"
      PMA_USER: root
      PMA_PASSWORD: root_secret
    depends_on:
      - mariadb
      - mysql